validate if codeflare-sdk version exists

diff --git a/.github/workflows/odh-notebooks-sync.yml b/.github/workflows/odh-notebooks-sync.yml
--- a/.github/workflows/odh-notebooks-sync.yml
+++ b/.github/workflows/odh-notebooks-sync.yml
@@ -51,45 +51,61 @@ jobs:
             3.8
             3.9
 
-      - name: Install pipenv
-        run: pip install pipenv
+      - name: Install pipenv and pip-versions
+        run: pip install pipenv pip-versions
 
       - name: Update Pipfiles in accordance with Codeflare-SDK latest release
         run: |
-          # list all Pipfile paths having Codeflare-SDK listed
-          paths+=($(grep -rl 'codeflare-sdk = "~=.*"'))
-          # Extracting only directories from file paths, excluding a `.gitworkflow` directory
-          directories=()
-          exclude_directories=(
-            ".git/objects/pack"
-            ".github/workflows/",
-          )
-          for path in "${paths[@]}"; do
-            current_dir=$(dirname "$path")
-            #Check if current_dir is not in exclude_directories list
-            if [[ ! "${exclude_directories[@]}" =~ "$current_dir" ]]; then
-              #Check if Pipfile exists in current_dir
-              if [ -f "$current_dir/Pipfile" ];then
-                directories+=("$current_dir")
+          package_name=codeflare-sdk
+          # Get the list of available versions for the package
+          if ! versions=$(pipenv run pip-versions list $package_name);then
+            echo "Failed to retrieve versions for $package_name"
+            exit 1
+          fi
+          # Check if the desired version exists in the list
+          if echo "$versions" | grep -q "${CODEFLARE_RELEASE_VERSION}"; then
+            echo "Version ${CODEFLARE_RELEASE_VERSION} is available for $package_name"
+            # list all Pipfile paths having Codeflare-SDK listed
+            paths+=($(grep -rl "${package_name} = \"~=.*\""))
+            # Extracting only directories from file paths, excluding a `.gitworkflow` directory
+            directories=()
+            exclude_directories=(
+              ".git/objects/pack"
+              ".github/workflows/",
+            )
+            for path in "${paths[@]}"; do
+              current_dir=$(dirname "$path")
+              #Check if current_dir is not in exclude_directories list
+              if [[ ! "${exclude_directories[@]}" =~ "$current_dir" ]]; then
+                #Check if Pipfile exists in current_dir
+                if [ -f "$current_dir/Pipfile" ];then
+                  directories+=("$current_dir")
+                fi
               fi
-            fi
-          done
-          # Remove duplicates
-          directories=($(echo "${directories[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
-          # Print the directories for verification
-          echo "Directories (Start updating Pipfile in these below directories in accordance with Codeflare-SDK latest release):"
-          for dir in "${directories[@]}"; do
-            echo "- $dir"
-          done
-          # iterate over the directories and update Pipfile
-          counter=0
-          total=${#directories[@]}
-          for dir in "${directories[@]}"; do
-            counter=$((counter+1))
-            echo "--Processing directory $counter '$dir' of total $total"
-            cd "$dir" && pipenv install codeflare-sdk~="${CODEFLARE_RELEASE_VERSION}" && pipenv --rm && cd -
-            echo "$((total-counter)) directories remaining.."
-          done
+            done
+            # Remove duplicates
+            directories=($(echo "${directories[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
+            # Print the directories for verification
+            echo "Directories (Start updating Pipfile in these below directories in accordance with Codeflare-SDK latest release):"
+            for dir in "${directories[@]}"; do
+              echo "- $dir"
+            done
+            # iterate over the directories and update Pipfile
+            counter=0
+            total=${#directories[@]}
+            for dir in "${directories[@]}"; do
+              counter=$((counter+1))
+              echo "--Processing directory $counter '$dir' of total $total"
+              cd "$dir" && pipenv install ${package_name}~="${CODEFLARE_RELEASE_VERSION}" && pipenv --rm && cd -
+              echo "$((total-counter)) directories remaining.."
+            done
+          else
+            versions_list=$(echo "$versions" | tr '\n' '   ' | sed 's/, $//')
+            versions="${versions_list%,}"
+            echo "Version '${CODEFLARE_RELEASE_VERSION}' is not available for $package_name"
+            echo "Available versions for $package_name: $versions"
+            exit 1
+          fi
 
       - name: Push changes
         run: |
